name: lint

on:
  push:
  pull_request:

jobs:
  lint-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++-14]
        target: [Debug]
        std: [11, 20]
        unwind: [
          CPPTRACE_UNWIND_WITH_EXECINFO,
          CPPTRACE_UNWIND_WITH_NOTHING,
        ]
        symbols: [
          CPPTRACE_GET_SYMBOLS_WITH_LIBBACKTRACE,
          CPPTRACE_GET_SYMBOLS_WITH_LIBDL,
          CPPTRACE_GET_SYMBOLS_WITH_ADDR2LINE,
          CPPTRACE_GET_SYMBOLS_WITH_NOTHING,
        ]
        demangle: [
          CPPTRACE_DEMANGLE_WITH_CXXABI,
          CPPTRACE_DEMANGLE_WITH_NOTHING,
        ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10 libgcc-10-dev
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_SHARED_LIBS=On \
            -DCPPTRACE_RUN_CLANG_TIDY=On \
            -DCPPTRACE_BACKTRACE_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/include/backtrace.h
           make
  lint-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++]
        target: [Debug]
        std: [11, 20]
        unwind: [
          CPPTRACE_UNWIND_WITH_WINAPI,
          CPPTRACE_UNWIND_WITH_NOTHING,
        ]
        symbols: [
          CPPTRACE_GET_SYMBOLS_WITH_DBGHELP,
          CPPTRACE_GET_SYMBOLS_WITH_NOTHING,
        ]
        demangle: [
          # CPPTRACE_DEMANGLE_WITH_CXXABI,
          CPPTRACE_DEMANGLE_WITH_NOTHING,
        ]
        exclude:
          - demangle: CPPTRACE_DEMANGLE_WITH_CXXABI
            compiler: cl
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DCMAKE_CXX_STANDARD=${{matrix.std}} `
            -DCPPTRACE_RUN_CLANG_TIDY=On `
            -D${{matrix.unwind}}=On `
            -D${{matrix.symbols}}=On `
            -D${{matrix.demangle}}=On
           msbuild .\cpptrace.sln
