name: performance-test

on:
  push:
  pull_request:

jobs:
  performancetest-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-11, clang++-14]
        config: [
          -DSPEEDTEST_DWARF4=On,
          -DSPEEDTEST_DWARF5=On
        ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-11 g++-11 libgcc-11-dev
    - name: build and speedtest
      run: |
           mkdir -p build
           cd build
           cmake .. -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=Release
           make -j
           mkdir -p ../test/speedtest/build
           cd ../test/speedtest/build
           cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            ${{matrix.config}}
           make -j
    - name: test
      working-directory: test/speedtest/build
      run: |
           ./speedtest | python3 ../../../ci/speedtest.py ${{matrix.compiler}} ${{matrix.config}}

  performancetest-windows:
   runs-on: windows-2019
   strategy:
     fail-fast: false
     matrix:
       compiler: [cl, clang++]
   steps:
   - uses: actions/checkout@v2
   - name: Enable Developer Command Prompt
     uses: ilammy/msvc-dev-cmd@v1.10.0
   - name: build and speedtest
     run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=Release
          msbuild .\cpptrace.sln
          mkdir -p ../test/speedtest/build
          cd ../test/speedtest/build
          cmake .. `
            -DCMAKE_BUILD_TYPE=Debug `
            ${{matrix.config}}
          msbuild .\cpptrace-speedtest.sln
   - name: test
     working-directory: test/speedtest/build
     run: |
          .\Debug\speedtest.exe | python3 ../../../ci/speedtest.py ${{matrix.config}}
