name: performance-test

on:
  push:
  pull_request:

# TODO: Test statically linked

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, clang++-14]
        target: [Debug]
        std: [11, 20]
        config: [
          "-DCPPTRACE_FULL_TRACE_WITH_LIBBACKTRACE=On",
          "-DCPPTRACE_GET_SYMBOLS_WITH_ADDR2LINE=On -DCPPTRACE_BUILD_SPEEDTEST_DWARF4",
          "-DCPPTRACE_GET_SYMBOLS_WITH_ADDR2LINE=On -DCPPTRACE_BUILD_SPEEDTEST_DWARF5"
        ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10 libgcc-10-dev
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_CXX_STANDARD=${{matrix.std}} \
            ${{matrix.config}} \
            -DCPPTRACE_BACKTRACE_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/include/backtrace.h \
            -DCPPTRACE_BUILD_SPEEDTEST=On \
            -DBUILD_SHARED_LIBS=On
           make
    - name: test
      working-directory: build
      run: |
           addr2line --version
           time addr2line -e lib/libgtest.so.1.12.1 -f -C -p << EOF
           e4925
           dc87f
           b782e
           b82fd
           b8c48
           c8aee
           e5e37
           dda9b
           c70dd
           EOF
           time addr2line -e speedtest -f -C -p << EOF
           3686
           3545
           EOF
           echo FOOBAR
           ls -l lib/libgtest.so.1.12.1
           readelf --debug-dump=info lib/libgtest.so.1.12.1 | head -n10
           echo FOOBAR
           ./speedtest | python3 ../test/speedtest.py ${{matrix.config}}
  test-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler: [cl, clang++]
        target: [Debug]
        std: [11, 20]
        config: [
          "-DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP=On"
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DCMAKE_CXX_STANDARD=${{matrix.std}} `
            ${{matrix.config}}=On `
            -DCPPTRACE_BUILD_SPEEDTEST=On `
            -DBUILD_SHARED_LIBS=On
           msbuild .\cpptrace.sln
    - name: test
      working-directory: build
      run: |
           .\${{matrix.target}}\speedtest.exe | python3 ../test/speedtest.py ${{matrix.config}}
